### PR TITLE
Start terraform provisioning

### PR DESCRIPTION
**Pull request by lispyclouds**
Start to provision the `Medium` instance on Exoscale using the ansible files.

- Initiates the Ansible provisioning via Terraform userdata upon cloud init.

### CODE REVIEW

**Review by bombaywalla — COMMENTED** [review]
You don't need to pass in github_username to the setup_user role if it is the same as the username. OTOH, it doesn't hurt and it documents.

I am not sure how the hosts file you have would interact with the Vagrant provisioning. In particular, there are two provisioners for Vagrant: ansible and ansible_local. Would the ansible_connection=local impact the ansible provisioner in Vagrant? Would you try bringing up a vagrant and provision it on your branch?

Assuming that works, I am okay with the changes. With the caveat that while I am familiar with Terraform, I am not familiar enough with Exoscale.

**Comment by lispyclouds** [comment]
@bombaywalla ,
> You don't need to pass in github_username to the setup_user role if it is the same as the username. OTOH, it doesn't hurt and it documents.

I tried it normally but the SSH keys weren't coming for some reason. Will have a deeper look.

> I am not sure how the hosts file you have would interact with the Vagrant provisioning. In particular, there are two provisioners for Vagrant: ansible and ansible_local. Would the ansible_connection=local impact the ansible provisioner in Vagrant? Would you try bringing up a vagrant and provision it on your branch?

AFAIK, ansible shouldnt pick up the hosts file unless passed explicitly via `-i` or in /etc/ansible. Vagrant provisioning worked out fine.

> Assuming that works, I am okay with the changes. With the caveat that while I am familiar with Terraform, I am not familiar enough with Exoscale.

Exoscale is quite similar to AWS and is quite Terraform friendly. Check out these links
- https://www.exoscale.com/syslog/terraform-with-exoscale/
- https://github.com/exoscale/terraform-provider-exoscale/tree/master/examples

**Comment by bombaywalla** [comment]
> I tried it normally but the SSH keys weren't coming for some reason. Will have a deeper look.

Would you try and see if you can login into the Vagrant instance?

> AFAIK, ansible shouldnt pick up the hosts file unless passed explicitly via `-i` or in /etc/ansible. Vagrant provisioning worked out fine.

Thanks for checking.

Thanks for the Exoscale links.
I'll approve the PR separately,

**Comment by lispyclouds** [comment]
I checked the `.ssh` dirs in the home of the users and it contained some garbled keys in `authorized_keys`. Was proper only when I added in the `github_username`

Also https://angristan.xyz/how-to-use-non-aws-s3-backend-terraform/ was useful for me too

**Review by bombaywalla — APPROVED** [review]
Good to go. Thanks.

**Pull request merged**
