### PR TITLE
Implement Secrets

### PR DESCRIPTION
**Pull request by lispyclouds**
Implements an initial version of automated secret management.
- Commits GPG encrypted the secrets file.
  - Currently has @lispyclouds, @victorb and @bombaywalla 's creds. @plexus need yours here.
- Sets up terraform to render the file into the userdata and it barfs it into the right place on the server.
- Adds instructions.

NB: The `exoscale_api_keys.sh` in .gitignore is a helper file I use to load keys.

### CODE REVIEW

**Review by bombaywalla — COMMENTED** [review]
- Would it help to also add, to the README, the gpg commands to encrypt the secrets file? That way, the maintainers can copy/paste the commands to add the new maintainer.
- The gpg decrypt command (in the README) sends the output to clojurians_log_secrets.yml in the clojurians_log dir. Might it help to instead put it directly into clojurians_log/playbooks/vars/ instead? That will then also work for the Vagrant provisioning. If you do decide to do that, you'll need to update the path in userdata.sh.tmpl.

**Comment by lispyclouds** [comment]
done

**Review by bombaywalla — COMMENTED** [review]
I think I was not being clear enough earlier.
I meant that the clojurians_log_secrets.yml.gpg would be in clojurians_log/playbooks/vars/ not in clojurians_log.
You'd then cd to clojurians_log/playbooks/vars/ and run the gpg --decrypt.

Also, in the README, where you added the commands for the gpg encrypt, I think the encrypted file is missing.

**Comment by lispyclouds** [comment]
@bombaywalla pushed the changes. the encrypted file isn't needed as it produces a file with `<filename>.gpg` by default.

**Review by bombaywalla — APPROVED** [review]
Looks good.
Thanks.

**Pull request merged**
